// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingPlannerRedo.Models;

namespace WeddingPlannerRedo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeddingPlannerRedo.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WeddingPlannerRedo.Models.WeddingGuest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IsAttending");

                    b.Property<int>("PlanId");

                    b.Property<int>("UserId");

                    b.HasKey("GuestId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("WeddingGuests");
                });

            modelBuilder.Entity("WeddingPlannerRedo.Models.WeddingPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CreatorId");

                    b.Property<string>("Duration")
                        .IsRequired();

                    b.Property<DateTime?>("PlayDate")
                        .IsRequired();

                    b.Property<DateTime?>("PlayTime")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("WedderOne")
                        .IsRequired();

                    b.Property<string>("WeddingAddress")
                        .IsRequired();

                    b.HasKey("PlanId");

                    b.HasIndex("CreatorId");

                    b.ToTable("WeddingPlans");
                });

            modelBuilder.Entity("WeddingPlannerRedo.Models.WeddingGuest", b =>
                {
                    b.HasOne("WeddingPlannerRedo.Models.WeddingPlan", "WeddingPlan")
                        .WithMany("Guests")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WeddingPlannerRedo.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WeddingPlannerRedo.Models.WeddingPlan", b =>
                {
                    b.HasOne("WeddingPlannerRedo.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
